#***************************************************    
# * Title: UUV Simulator   
# * Author: The UUV Simulator Authors  
# * Date: 2016      
# * Availability: https://uuvsimulator.github.io/
#***************************************************

float64 velocity
float64 horizontal_angle
float64 vertical_angle
---
bool success
