#***************************************************    
# * Title: UUV Simulator   
# * Author: The UUV Simulator Authors  
# * Date: 2016      
# * Availability: https://uuvsimulator.github.io/
#***************************************************

# Practical salinity units
string PSU="psu"
# Parts per million
string PPM="ppm"
# Parts per thousand
string PPT="ppt"

std_msgs/Header header
float64 salinity
float64 variance
string unit
